Added the full ArgoCD chart and created documentation for it
distributed-technologies/argo-cd pull request #1
Opened 2021-03-17 14:11 UTC by jaxels10

Added the full ArgoCD chart.

2021-03-17 14:27 UTC, jacobcrawford requested changes
I don't know what I am looking at, but there is a lot of missing newlines. That i can say.

2021-03-17 14:27 UTC, jacobcrawford commented on chart/Chart.yaml
> +version: 2.17.0
Should we not start at a lower version?

2021-03-17 14:27 UTC, jacobcrawford commented on chart/charts/redis-ha/templates/redis-ha-exporter-script-configmap.yaml
> +{{- end }}
missing newline

2021-03-17 14:27 UTC, jacobcrawford commented on chart/charts/redis-ha/templates/sentinel-auth-secret.yaml
> +{{- end -}}
missing newline

2021-03-18 06:48 UTC, jaxels10 commented on chart/Chart.yaml
> +version: 2.17.0
I have updated the file to include a bit more info and also changed the version to 0.1.0

2021-03-18 06:55 UTC, jaxels10 commented on chart/charts/redis-ha/templates/sentinel-auth-secret.yaml
> +{{- end -}}
Where do you think it needs a newline?

2021-03-18 06:56 UTC, jaxels10 commented on chart/charts/redis-ha/templates/redis-ha-exporter-script-configmap.yaml
> +{{- end }}
Where do you think it needs a newline?

2021-03-18 07:01 UTC, jaxels10 commented on chart/charts/redis-ha/templates/redis-ha-exporter-script-configmap.yaml
> +{{- end }}
Added the newline in a new commit

2021-03-18 07:01 UTC, jaxels10 commented on chart/charts/redis-ha/templates/sentinel-auth-secret.yaml
> +{{- end -}}
Added the newline in a new commit

2021-03-18 09:54 UTC, jacobcrawford approved these changes
easy

2021-03-18 09:54 UTC, merged